name: CI
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [main]  
  workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Scripts
        run: |
          docker build -t app .
          docker login - u uruser -p urpass
          docker tag app reach2vikashkr/tw
          docker push reach2vikashkr/tw
        
        
   
